# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Brad Burega
title: MSc in Computing Science Student
email: buregab@gmail.com
website: buregab.github.io

# Social links
# twitter_username: facespics
github_username:  buregab
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: brad-burega
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Brad. I'm a MSc in Computing Science student at the University of Alberta working with Michael Bowling. I'm interested in 
  reinforcement learning and machine learning more generally. Previously I was a Search and Data Mining Engineer at Yelp. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
